/**
 * MrSeven590-pinyin-match (Android)
 *
 * Pure UTS implementation (no native dependencies).
 */

import { GetInitials, PinyinMatch } from '../interface.uts'
import { getInitials as _getInitials, pinyinMatch as _pinyinMatch } from '../pinyin-match.uts'

export const pinyinMatch: PinyinMatch = function (input: string, keyword: string): boolean {
  return _pinyinMatch(input, keyword)
}

export const getInitials: GetInitials = function (cn: string): string {
  return _getInitials(cn)
}

